// Seed data & constants for ForgeFit

export const MUSCLES = [
  { id: 'chest', name: 'Klatka piersiowa', short: 'Klatka', group: 'upper' },
  { id: 'back', name: 'Plecy', short: 'Plecy', group: 'upper' },
  { id: 'shoulders', name: 'Barki', short: 'Barki', group: 'upper' },
  { id: 'biceps', name: 'Biceps', short: 'Biceps', group: 'upper' },
  { id: 'triceps', name: 'Triceps', short: 'Triceps', group: 'upper' },
  { id: 'forearms', name: 'Przedramiona', short: 'Przedram.', group: 'upper' },
  { id: 'abs', name: 'Brzuch', short: 'Brzuch', group: 'core' },
  { id: 'glutes', name: 'Pośladki', short: 'Pośladki', group: 'lower' },
  { id: 'quads', name: 'Czworogłowe uda', short: 'Quads', group: 'lower' },
  { id: 'hamstrings', name: 'Dwugłowe uda', short: 'Hamstring', group: 'lower' },
  { id: 'calves', name: 'Łydki', short: 'Łydki', group: 'lower' },
  { id: 'fullbody', name: 'Całe ciało', short: 'Full', group: 'full' }
];

export const EQUIPMENT = [
  { id: 'barbell', name: 'Sztanga' },
  { id: 'dumbbell', name: 'Hantle' },
  { id: 'machine', name: 'Maszyny' },
  { id: 'cable', name: 'Wyciąg' },
  { id: 'kettlebell', name: 'Kettlebell' },
  { id: 'bands', name: 'Gumy' },
  { id: 'bodyweight', name: 'Masa ciała' },
  { id: 'pullup', name: 'Drążek' },
  { id: 'bench', name: 'Ławka' },
  { id: 'other', name: 'Inne' }
];

export const EXERCISE_TYPES = [
  { id: 'strength', name: 'Siłowe' },
  { id: 'hypertrophy', name: 'Hipertrofia' },
  { id: 'isolation', name: 'Izolowane' },
  { id: 'compound', name: 'Wielostawowe' },
  { id: 'warmup', name: 'Rozgrzewkowe' },
  { id: 'mobility', name: 'Mobilizacyjne' },
  { id: 'cardio', name: 'Cardio' },
  { id: 'conditioning', name: 'Kondycyjne' },
  { id: 'stretching', name: 'Stretching' }
];

export const SET_TYPES = [
  { id: 'working', name: 'Seria robocza', color: 'forge' },
  { id: 'warmup', name: 'Rozgrzewkowa', color: 'blue' },
  { id: 'feeder', name: 'Wprowadzająca', color: 'indigo' },
  { id: 'failure', name: 'Do upadku', color: 'red' },
  { id: 'technique', name: 'Techniczna', color: 'purple' },
  { id: 'dropset', name: 'Drop set', color: 'orange' },
  { id: 'restpause', name: 'Rest-pause', color: 'yellow' },
  { id: 'myoreps', name: 'Myo-reps', color: 'pink' },
  { id: 'backoff', name: 'Back-off', color: 'cyan' },
  { id: 'amrap', name: 'AMRAP', color: 'green' },
  { id: 'special', name: 'Specjalna', color: 'gray' }
];

export const GOALS = [
  { id: 'hypertrophy', name: 'Budowa masy mięśniowej' },
  { id: 'cut', name: 'Redukcja' },
  { id: 'strength', name: 'Siła' },
  { id: 'conditioning', name: 'Poprawa kondycji' },
  { id: 'recomp', name: 'Recomposition' },
  { id: 'general', name: 'Ogólna sprawność' }
];

export const LEVELS = [
  { id: 'beginner', name: 'Początkujący' },
  { id: 'intermediate', name: 'Średniozaawansowany' },
  { id: 'advanced', name: 'Zaawansowany' }
];

export const SEED_EXERCISES = [
  {
    id: 'ex-bp',
    name: 'Wyciskanie sztangi na ławce płaskiej',
    nameEn: 'Barbell Bench Press',
    primary: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Klasyczne ćwiczenie na klatkę piersiową. Leżąc na ławce, wyciskaj sztangę z klatki do pełnego wyprostu.',
    instructions: '1. Połóż się na ławce, stopy stabilnie na podłodze.\n2. Chwyć sztangę szerzej niż barki.\n3. Opuść kontrolowanie do klatki (łokcie ~45°).\n4. Wypchnij do góry, nie blokując łokci.',
    commonMistakes: 'Odbijanie sztangi od klatki, uniesione biodra, zbyt szeroki chwyt, brak kontroli w dole.',
    tips: 'Napnij łopatki i wciśnij w ławkę. Oddychaj: wdech w dole, wydech przy wycisku.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-squat',
    name: 'Przysiad ze sztangą',
    nameEn: 'Barbell Back Squat',
    primary: 'quads',
    secondary: ['glutes', 'hamstrings', 'abs'],
    equipment: ['barbell'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Król ćwiczeń na dolną część ciała. Głęboki przysiad z obciążeniem na barkach.',
    instructions: '1. Sztanga na górze trapezu.\n2. Stopy na szerokość barków, palce lekko na zewnątrz.\n3. Zepchnij biodra w tył i w dół do równoległości lub niżej.\n4. Wróć mocno do góry, napinając pośladki.',
    commonMistakes: 'Kolana zapadają do środka, zaokrąglone plecy, pięty odrywają się od ziemi.',
    tips: 'Patrz prosto przed siebie. Kolana w linii ze stopami. Napnij core.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-dl',
    name: 'Martwy ciąg',
    nameEn: 'Conventional Deadlift',
    primary: 'back',
    secondary: ['hamstrings', 'glutes', 'forearms'],
    equipment: ['barbell'],
    type: 'compound',
    difficulty: 'advanced',
    description: 'Podnoszenie sztangi z ziemi do pozycji stojącej. Buduje siłę całego łańcucha tylnego.',
    instructions: '1. Stopy pod sztangą, chwyt na zewnątrz kolan.\n2. Biodra nisko, plecy proste, klatka wypchnięta.\n3. Pchnij nogami i jednocześnie prostuj tułów.\n4. Zablokuj biodra na górze, nie odchylaj się.',
    commonMistakes: 'Zaokrąglone dolne plecy, szarpanie, zbyt daleko sztanga od ciała.',
    tips: 'Sztanga blisko goleni. „Zepchnij podłogę”. Core mocno napięty.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-ohp',
    name: 'Wyciskanie sztangi nad głowę',
    nameEn: 'Overhead Press',
    primary: 'shoulders',
    secondary: ['triceps', 'abs'],
    equipment: ['barbell'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Wyciskanie stojąc – doskonałe na barki i stabilność core.',
    instructions: '1. Sztanga na przednich barkach, łokcie pod przodem.\n2. Wypchnij prosto w górę, głowa lekko do tyłu.\n3. Zablokuj nad głową, potem kontrolowanie opuść.',
    commonMistakes: 'Odchylanie tułowia, wyciskanie do przodu zamiast w górę.',
    tips: 'Napnij pośladki i brzuch. Ścieżka sztangi blisko twarzy.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-row',
    name: 'Wiosłowanie sztangą w opadzie',
    nameEn: 'Barbell Bent Over Row',
    primary: 'back',
    secondary: ['biceps', 'shoulders'],
    equipment: ['barbell'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Buduje grubość i siłę pleców.',
    instructions: '1. Pochyl tułów ~45°, plecy proste.\n2. Przyciągnij sztangę do dolnej klatki/brzucha.\n3. Łokcie blisko ciała, ściągnij łopatki.\n4. Opuść kontrolowanie.',
    commonMistakes: 'Zbyt duży ruch bioder, zaokrąglone plecy, szarpanie.',
    tips: 'Myśl o ściąganiu łokci, nie o podnoszeniu sztangi rękami.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-pullup',
    name: 'Podciąganie na drążku',
    nameEn: 'Pull-up',
    primary: 'back',
    secondary: ['biceps', 'forearms'],
    equipment: ['pullup'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Jedno z najlepszych ćwiczeń na szerokość pleców.',
    instructions: '1. Chwyt nadchwytem, nieco szerzej niż barki.\n2. Podciągnij się aż broda nad drążek.\n3. Opuść kontrolowanie do pełnego wyprostu.',
    commonMistakes: 'Kiwanie nogami, niepełny zakres, szarpanie.',
    tips: 'Inicjuj ruchem łopatek. Core napięty, nogi nieruchome.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-rdl',
    name: 'Martwy ciąg rumuński',
    nameEn: 'Romanian Deadlift',
    primary: 'hamstrings',
    secondary: ['glutes', 'back'],
    equipment: ['barbell'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Skupia się na tylnej taśmie – dwugłowe i pośladki.',
    instructions: '1. Stojąc, sztanga w dłoniach.\n2. Biodra w tył, lekko ugięte kolana, tułów opada.\n3. Poczuj rozciąganie w dwugłowych.\n4. Wróć napinając pośladki.',
    commonMistakes: 'Zbyt duże ugięcie kolan, zaokrąglone plecy.',
    tips: 'Sztanga blisko nóg. Ruch z bioder, nie z kolan.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-dbpress',
    name: 'Wyciskanie hantli na ławce',
    nameEn: 'Dumbbell Bench Press',
    primary: 'chest',
    secondary: ['triceps', 'shoulders'],
    equipment: ['dumbbell', 'bench'],
    type: 'compound',
    difficulty: 'beginner',
    description: 'Większy zakres ruchu niż sztanga, świetne czucie mięśnia.',
    instructions: '1. Hantle na wysokości klatki, dłonie do przodu.\n2. Wypchnij do góry, zbliżając hantle lekko.\n3. Opuść wolno poniżej poziomu klatki.',
    commonMistakes: 'Zbyt duże rozwarcie łokci, brak kontroli.',
    tips: 'Napnij klatkę na dole. Nie uderzaj hantlami o siebie na górze.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-latpd',
    name: 'Ściąganie wyciągu górnego',
    nameEn: 'Lat Pulldown',
    primary: 'back',
    secondary: ['biceps'],
    equipment: ['cable'],
    type: 'compound',
    difficulty: 'beginner',
    description: 'Alternatywa dla podciągania, łatwiejsza do progresji.',
    instructions: '1. Chwyt szeroki, nadchwyt.\n2. Ściągnij drążek do górnej klatki.\n3. Ściągnij łopatki, łokcie w dół i do tyłu.\n4. Wróć kontrolowanie.',
    commonMistakes: 'Odchylanie tułowia, używanie impetu.',
    tips: 'Początek ruchu od łopatek. Tułów stabilny.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-legpress',
    name: 'Wypychanie nóg na suwnicy',
    nameEn: 'Leg Press',
    primary: 'quads',
    secondary: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    type: 'compound',
    difficulty: 'beginner',
    description: 'Bezpieczna alternatywa dla przysiadów przy dużych obciążeniach.',
    instructions: '1. Stopy na platformie na szerokość barków.\n2. Opuść do ~90° w kolanach.\n3. Wypchnij bez pełnego blokowania kolan.',
    commonMistakes: 'Kolana do środka, zbyt głębokie zejście z zaokrągleniem pleców.',
    tips: 'Plecy dociśnięte do oparcia. Nie odrywaj bioder.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-curl',
    name: 'Uginanie przedramion ze sztangą',
    nameEn: 'Barbell Curl',
    primary: 'biceps',
    secondary: ['forearms'],
    equipment: ['barbell'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Klasyczne ćwiczenie na biceps.',
    instructions: '1. Stojąc, sztanga w dłoniach, łokcie przy tułowiu.\n2. Ugiń do pełnego skurczu.\n3. Opuść kontrolowanie.',
    commonMistakes: 'Huśtanie tułowiem, łokcie odchodzą do przodu.',
    tips: 'Łokcie nieruchome. Pełny zakres, kontrola ekscentryki.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-skull',
    name: 'Prostowanie przedramion leżąc (skull crusher)',
    nameEn: 'Skull Crusher',
    primary: 'triceps',
    secondary: [],
    equipment: ['barbell', 'bench'],
    type: 'isolation',
    difficulty: 'intermediate',
    description: 'Izolacja tricepsa z dużym napięciem.',
    instructions: '1. Leżąc, sztanga nad klatką, ramiona prostopadle.\n2. Ugiń tylko w łokciach, opuszczając do czoła/za głowę.\n3. Wypchnij do wyprostu.',
    commonMistakes: 'Ruch w barkach, zbyt szeroki chwyt.',
    tips: 'Łokcie skierowane do sufitu. Kontroluj w dole.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-lateral',
    name: 'Unoszenie hantli bokiem',
    nameEn: 'Dumbbell Lateral Raise',
    primary: 'shoulders',
    secondary: [],
    equipment: ['dumbbell'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Buduje boczną część barków (delty boczne).',
    instructions: '1. Hantle wzdłuż ciała, lekko ugięte łokcie.\n2. Unieś na boki do poziomu barków.\n3. Opuść wolno.',
    commonMistakes: 'Zbyt ciężkie hantle → huśtanie, unoszenie powyżej poziomu.',
    tips: 'Myśl o „wylewaniu z dzbanków”. Lekki ciężar, pełna kontrola.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-hipthrust',
    name: 'Wypychanie bioder ze sztangą',
    nameEn: 'Barbell Hip Thrust',
    primary: 'glutes',
    secondary: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Najlepsze ćwiczenie na pośladki.',
    instructions: '1. Górne plecy na ławce, sztanga na biodrach.\n2. Stopy na szerokość bioder.\n3. Wypchnij biodra w górę do pełnego wyprostu.\n4. Napnij pośladki na górze 1s.',
    commonMistakes: 'Przeprost w odcinku lędźwiowym, stopy za daleko.',
    tips: 'Broda lekko do klatki. Ruch z bioder, nie z pleców.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-calfraise',
    name: 'Wspięcia na palce stojąc',
    nameEn: 'Standing Calf Raise',
    primary: 'calves',
    secondary: [],
    equipment: ['machine', 'bodyweight'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Buduje łydki – zarówno brzuchaty jak i płaszczkowaty przy pełnym zakresie.',
    instructions: '1. Pełne zejście (rozciągnięcie).\n2. Wspięcie na maksymalne.\n3. Pauza 1s na górze.',
    commonMistakes: 'Zbyt szybkie ruchy, niepełny zakres.',
    tips: 'Pełny zakres + kontrola. Można robić jednostronnie.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-plank',
    name: 'Deska (plank)',
    nameEn: 'Plank',
    primary: 'abs',
    secondary: ['shoulders'],
    equipment: ['bodyweight'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Izometryczne ćwiczenie na core.',
    instructions: '1. Podpór na przedramionach i palcach stóp.\n2. Ciało w linii prostej.\n3. Napnij brzuch i pośladki.\n4. Oddychaj spokojnie.',
    commonMistakes: 'Opadające biodra, uniesione biodra, wstrzymywanie oddechu.',
    tips: 'Myśl o „wciąganiu pępka”. Nie trzymaj oddechu.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-facepull',
    name: 'Face pull na wyciągu',
    nameEn: 'Face Pull',
    primary: 'shoulders',
    secondary: ['back'],
    equipment: ['cable'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Zdrowie barków + tylne delty i rotator cuff.',
    instructions: '1. Lina na wysokości twarzy.\n2. Przyciągnij do twarzy, rozsuwając końce.\n3. Łokcie wysoko, zewnętrzna rotacja.',
    commonMistakes: 'Zbyt ciężki ciężar, brak rotacji zewnętrznej.',
    tips: 'Lekki ciężar, fokus na ściągnięcie i rotację.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-lunges',
    name: 'Wykroki z hantlami',
    nameEn: 'Dumbbell Walking Lunges',
    primary: 'quads',
    secondary: ['glutes', 'hamstrings'],
    equipment: ['dumbbell'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Jednostronne ćwiczenie nóg – stabilność + siła.',
    instructions: '1. Krok do przodu, opuść tylne kolano.\n2. Przednie kolano nad kostką.\n3. Odepchnij się i następny krok.',
    commonMistakes: 'Kolano przedniego wychodzi za palce, tułów pochylony.',
    tips: 'Krok wystarczająco długi. Tułów wyprostowany.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-dips',
    name: 'Pompki na poręczach',
    nameEn: 'Dips',
    primary: 'triceps',
    secondary: ['chest', 'shoulders'],
    equipment: ['bodyweight', 'other'],
    type: 'compound',
    difficulty: 'intermediate',
    description: 'Świetne na triceps i dolną klatkę.',
    instructions: '1. Podpór na poręczach, ramiona proste.\n2. Opuść aż barki poniżej łokci.\n3. Wypchnij do góry.',
    commonMistakes: 'Zbyt duże pochylenie (wtedy więcej klatki), niepełny zakres.',
    tips: 'Tułów prawie pionowy = więcej tricepsa. Kontroluj dół.',
    images: [],
    isCustom: false,
    isPublic: true
  },
  {
    id: 'ex-cablefly',
    name: 'Rozpiętki na wyciągu',
    nameEn: 'Cable Fly',
    primary: 'chest',
    secondary: [],
    equipment: ['cable'],
    type: 'isolation',
    difficulty: 'beginner',
    description: 'Izolacja klatki z ciągłym napięciem.',
    instructions: '1. Wyciągi na wysokości klatki.\n2. Lekko ugięte łokcie, zbliż ręce przed sobą.\n3. Rozłóż kontrolowanie.',
    commonMistakes: 'Zbyt proste łokcie, używanie impetu.',
    tips: 'Myśl o „obejmowaniu drzewa”. Stałe napięcie.',
    images: [],
    isCustom: false,
    isPublic: true
  }
];

export const DEFAULT_PLATES = [
  { weight: 25, count: 4 },
  { weight: 20, count: 4 },
  { weight: 15, count: 2 },
  { weight: 10, count: 4 },
  { weight: 5, count: 4 },
  { weight: 2.5, count: 4 },
  { weight: 1.25, count: 4 },
  { weight: 0.5, count: 2 }
];

export const DEFAULT_BARS = [
  { id: 'olympic', name: 'Olimpijska', weight: 20 },
  { id: 'ez', name: 'Łamana (EZ)', weight: 8 },
  { id: 'custom', name: 'Własna', weight: 15 }
];

export const RECOVERY_HOURS = {
  chest: 48,
  back: 48,
  shoulders: 36,
  biceps: 36,
  triceps: 36,
  forearms: 24,
  abs: 24,
  glutes: 48,
  quads: 72,
  hamstrings: 48,
  calves: 36,
  fullbody: 72
};
